apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: argocd
spec:
  containers:
  - name: curl-container
    image: alpine:latest
    command: ["/bin/sh"]
    args: ["-c", "apk add --no-cache curl && exec sleep infinity"]
